// This enum was generated by Dialoguer
//	Do not modify this file, it will be overwritten by Dialoguer.
public enum DialoguerDialogues{
	Raccoon1 = 0,
	My_Second_Dialogue = 2,
	Temp = 3,
	MomDialogue = 4,
	Mom2 = 5,
	Mom3 = 6,
	Dad1 = 7,
	Dad2 = 8,
	ParentsEnd1 = 9,
	ParentsEnd2 = 10,
}
